---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: false
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: true
app_desc: a thin wrapper for Terraform that provides extra tools for working with
    multiple Terraform modules.
app_name: terragrunt
app_repo: https://github.com/gruntwork-io/terragrunt
app_type: standalone
app_website: https://terragrunt.gruntwork.io/
archive_enabled: false
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://github.com/gruntwork-io/terragrunt/releases/download/v{version}/SHA256SUMS
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    i386: '386'
    i686: '386'
    x86: '386'
    x86_64: amd64
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
custom_require_commands: ''
download_url: https://github.com/gruntwork-io/terragrunt/releases/download/v{version}/terragrunt_{os}_{arch}
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    terragrunt: bin/terragrunt
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-terragrunt
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-terragrunt.git
source_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
